bds_sport_view:
    path:     /admin/{nom}
    defaults: { _controller: BDSCoreBundle:Sport:view }
    
bds_sport_add:
    path:     /admin/sport/add
    defaults: { _controller: BDSCoreBundle:Sport:add }
    
bds_sport_delete:
    path:     /admin/{nom}/delete
    defaults: { _controller: BDSCoreBundle:Sport:delete }
    
bds_sport_edit:
    path:     /admin/{nom}/edit
    defaults: { _controller: BDSCoreBundle:Sport:edit }  
    
bds_sport_list:
    path:     /sport
    defaults: { _controller: BDSCoreBundle:Sport:list }
    
bds_sport_equipe:
    path:     /{nom}/equipe
    defaults: {_controller: BDSCoreBundle:Sport:equipe }
    
bds_sport_presentation:
    path:     /{domaine}/presentation
    defaults: {_controller: BDSCoreBundle:Sport:presentation }
    
bds_sport_presentation_edit:
    path:     /{domaine}/presentation/edit
    defaults: {_controller: BDSCoreBundle:Sport:presentationEdit }
    
bds_sport_motCapitaine:
    path:     /{domaine}/mot_du_capitaine
    defaults: {_controller: BDSCoreBundle:Sport:motCapitaine }

bds_sport_motCapitaineEdit:
    path:     /[{domaine}/mot_du_capitaine/edit
    defaults: {_controller: BDSCoreBundle:Sport:motCapitaineEdit }
   
    
    