# app/config/security.yml

security:
    encoders:
        BDS\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|bundles)/
            security: false
        public:
            pattern:  ^/(public|(login$))
            anonymous: true
            
        main:
            pattern:  ^/
            anonymous: false
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: bds_news_home 
            logout:
                path: fos_user_security_logout
                target: bds_news_home
            remember_me:
                key: %secret%

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }